pub mod action;
pub mod ai;
pub mod city;
pub mod combat;
pub mod economy;
pub mod error;
pub mod game;
pub mod ids;
pub mod map;
pub mod movement;
pub mod player;
pub mod resources;
pub mod rng;
pub mod scoring;
pub mod terrain;
pub mod tile;
pub mod turn;
pub mod unit;
pub mod world;

pub use action::PlayerAction;
pub use city::{City, CityProject, CityProjectKind};
pub use error::GameError;
pub use game::{Game, GameConfig, GameOutcome, GameState, TurnReport};
pub use ids::{CityId, PlayerId, TilePosition, TurnNumber, UnitId};
pub use player::Player;
pub use resources::{ResourceStockpile, ResourceYield};
pub use terrain::TerrainType;
pub use unit::{Unit, UnitKind};
pub use world::World;
